sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t ashwinmreddy/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true ashwinmreddy/docker-react npm run test